# 层级要求很严格  每一级前面两个空格
server:
  port: 8081

mybatis:
  type-aliases-package: com.usian.pojo
  mapper-locations: classpath:mappers/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.40.130:3306/delun
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
logging:
        level:
          com:
            usian:
              mapper: debug
